services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
#  planefinder:
#    image: 'planefinder'
#    ports:
#      - '7634:7634'
  database:
    image: 'mysql'
    ports:
      - '13306:3306'
    environment:
#      - 'MYSQL_USER=myuser'
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_ROOT_PASSWORD=secret'
  redis:
    image: 'redis'
    ports:
      - '16379:6379'
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  neo4j:
    image: 'neo4j'
    ports:
      - '7474'
      - '7687'
    environment:
      NEO4J_AUTH: neo4j/password