services:
  planefinder:
    image: 'planefinder'
    ports:
      - '7634:7634'
  database:
    image: 'mysql'
    ports:
      - '13306:3306'
    environment:
#      - 'MYSQL_USER=myuser'
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_ROOT_PASSWORD=secret'
  redis:
    image: 'redis'
    ports:
      - '16379:6379'